# Project information
site_name: ISTQB Education Material
site_url: https://github.com/fabianpg95/istqb-material

# Repository
repo_name: istqb-material
repo_url: https://github.com/fabianpg95/istqb-material

# Page tree
nav:
      - Fundamentals:
        - '1.-Content': 'fundamentals/1.-content.md'
        - '1.1-What is testing?': 'fundamentals/1.1-what-is-testing.md'
        - '1.2-Why is testing necessary?': 'fundamentals/1.2-why-test-neces.md'
        - '1.3- 7 test principles': 'fundamentals/1.3-seven-test-princ.md'
        - '1.4-Test process': 'fundamentals/1.4-test-process.md'
        - '1.5-Psycology of testing': 'fundamentals/1.5-psyco-of-testing.md'

      - Software lifecycle:
        - '1.-Content': 'software_lifecycle/1.-content.md'
        - '2.1-Objectives of testing': 'software_lifecycle/2.1-obj-testing-softw.md'
        - '2.2-Test levels': 'software_lifecycle/2.2-test-levels.md'
        - '2.3-Test types': 'software_lifecycle/2.3-test-types.md'
        - '2.4-Maintenance testing': 'software_lifecycle/2.4-maintenance-testing.md'

      - Static Test:
        - '1.-Content': 'static_test/1.-content.md'
        - '3.1-Static testing basics': 'static_test/3.1-stat-test-bas.md'
        - '3.2-Review process': 'static_test/3.2-review-process.md'

      - Test techniques:
        - '1.-Content': 'test_techniques/1.-content.md'
        - '4.1-Categories': 'test_techniques/4.1-cat-test-tech.md'
        - '4.2-Black Box': 'test_techniques/4.2-black-box-tech-tecn.md'
        - '4.3-White Box': 'test_techniques/4.3-white-box-tech.md'
        - '4.4-Experience Based': 'test_techniques/4.4-exp-based-tech.md'
      
      - Test management:
        - '1.-Content': 'test_management/1.-content.md'
        - '5.1-Test organization': 'test_management/5.1-test-org.md'
        - '5.2-Test plan estimation': 'test_management/5.2-test-plan-estim.md'
        - '5.3-Test monitoring & control': 'test_management/5.3-test-mon-control.md'
        - '5.4-Config management': 'test_management/5.4-config-manage.md'
        - '5.5-Risk testing': 'test_management/5.5-risk-testing.md'
        - '5.6-Defects management': 'test_management/5.6-defects-manage.md'

      - Tools support:
        - '1.-Content': 'tool_support/1.-content.md'
        - '6.1-Test tools consideration': 'tool_support/6.1-test-tool-consid.md'
        - '6.2-Effective use of tools': 'tool_support/6.2-effective-use-tools.md'
      - 'References': 'test_ref.md'

# Configurations
theme:
  name: "material"
  language: "en"

  # Configuration
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: "Roboto"
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - header.autohide
    - toc.autohide
    - content.code.annotate
  extra:
    version:
      method: mike

# Plugins
plugins:
  - search
  - git-revision-date

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

